### ISSUE TITLE
Install fails on Ubuntu Linux

### ISSUE THREAD

**Issue by Jkillelea** [electron-userland/electron-prebuilt#108]
Looks like install fails right at the end, with electron's install.js script.

```

12978 silly install printInstalled
12979 warn electron-test@1.0.0 No repository field.
12980 verbose stack Error: electron-prebuilt@0.37.2 postinstall: `node install.js`
12980 verbose stack spawn ENOENT
12980 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
12980 verbose stack     at emitTwo (events.js:87:13)
12980 verbose stack     at ChildProcess.emit (events.js:172:7)
12980 verbose stack     at maybeClose (internal/child_process.js:821:16)
12980 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
12981 verbose pkgid electron-prebuilt@0.37.2
12982 verbose cwd /home/user/projects/projects/electron
12983 error Linux 4.4.0-040400-generic
12984 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron-prebuilt" "--save-dev"
12985 error node v4.2.6
12986 error npm  v3.5.2
12987 error file sh
12988 error code ELIFECYCLE
12989 error errno ENOENT
12990 error syscall spawn
12991 error electron-prebuilt@0.37.2 postinstall: `node install.js`
12991 error spawn ENOENT
12992 error Failed at the electron-prebuilt@0.37.2 postinstall script 'node install.js'.
12992 error Make sure you have the latest version of node.js and npm installed.
12992 error If you do, this is most likely a problem with the electron-prebuilt package,
12992 error not with npm itself.
12992 error Tell the author that this fails on your system:
12992 error     node install.js
12992 error You can get information on how to open an issue for this project with:
12992 error     npm bugs electron-prebuilt
12992 error Or if that isn't available, you can get their info via:
12992 error     npm owner ls electron-prebuilt
12992 error There is likely additional logging output above.
12993 verbose exit [ 1, true ]

```

**Comment by vancezhao** [comment]
You should use sudo

**Comment by LongLiveCHIEF** [comment]
Sudo is *not* the problem.  It's an issue with platform identification, which causes the wrong `zip` to be downloaded, which therefore has the wrong `EOL` settings for Linux.

@Jkillelea quick question... what version of Ubuntu are you on? (15 or 16?), and secondly  are you using something like nvm to install node, or are you using `apt-get`?

Can you also run `npm config get prefix` and let me know what the output of that command is?

I just went through this issue myself, on Ubuntu Gnome 16.04. I had `nvm` installed before I ever installed node from `apt-get`, and the lack of a `system` node, caused issues when the installer calls node from the C compiler. (this happens when the `.zip` download is completed).

**Comment by Jkillelea** [comment]
I'm on 16.04, node was installed though the nodejs package in apt, I think.

user@hostname:~$ npm config get prefix
/usr/local

**Comment by LongLiveCHIEF** [comment]
yeah, this one might actually be an ownership problem.  You'll have to ensure that you're the owner of the directory the cache and the global node modules get downloaded to. 

`sudo chown -r $(whoami) /usr/local/bin/node`

**Comment by Jkillelea** [comment]
I don't actually have a /usr/local/bin/node.

user@hostname:/usr/local/bin$ ll | grep node
lrwxrwxrwx  1 root root   44 Mar 16 16:33 electron ->
../lib/node_modules/electron-prebuilt/cli.js
lrwxrwxrwx  1 root root   43 Mar 19 00:05 js2coffee ->
../lib/node_modules/js2coffee/bin/js2coffee*
lrwxrwxrwx  1 root root   38 Mar 16 16:45 npm ->
../lib/node_modules/npm/bin/npm-cli.js*

user@hostname:/usr/local/bin$ which node
/usr/bin/node

user@hostname:/usr/local/bin$ ll /usr/bin/ | grep node
lrwxrwxrwx  1 root root          53 Jan 22 12:04 apm ->
../share/atom/resources/app/apm/node_modules/.bin/apm*
lrwxrwxrwx  1 root root          15 Mar 19 00:05 node -> /usr/bin/nodejs*
lrwxrwxrwx  1 root root          33 Dec  7 15:39 node-gyp ->
../share/node-gyp/bin/node-gyp.js*
-rwxr-xr-x  1 root root    11187128 Feb  3 17:03 nodejs*

**Comment by LongLiveCHIEF** [comment]
I can tell you this... it's not an electron issue.  I'd recommend closing this issue, and check out Stack Overflow.  I could tell you to `chown` `/usr/local/bin`, but there's bound to be stuff in there other than node managed binaries (if not now, then likely later). And the chown'ing stuff is a rather brash stick.

I'd prefer you set your prefix to something like `~/.npm-local`, so that global modules and binaries will install somewhere you already have ownership of, and isn't typically a fs used for applications that could possibly bork your setup with the wrong permissions.

**Comment by Jkillelea** [comment]
I wound up fixing the issue by running the install scripts as root. I agree
that changing ownership on a whim is a bad idea.

I'll mark the issue as closed for now, but ideally, running it as sudo
shouldn't be necessary.

**Comment by LongLiveCHIEF** [comment]
If you tune into my next [Sunday Morning Ubuntu](https://livecoding.tv/longlivechief) show on [Livecoding.tv](https://livecoding.tv), and ping me that you're there, I'll walk through how to set everything up properly using my own system as an example.  10am central standard time.

**Comment by Jkillelea** [comment]
Thanks, I'll keep that in mind. However, I'm going to be pretty busy over the weekend. I'm not sure I'll make it.
