### ISSUE TITLE
Dont download on install

### ISSUE THREAD

**Issue by mcfedr** [electron-userland/electron-prebuilt#122]
It would be great if `electron-prebuilt` would not download when installing, and just download on demand.

Very often its unhelpful as either I dont want to use electron on a certain machine, or the platform is wrong and I have to redownload anyway.

**Comment by RnbWd** [comment]
Initially the repo was designed similar to something like 'on demand downloads' if I remember correctly, it installed a local copy of electron in every repo instead of using a central cache. So having central cache reduces  the redundancy. I'm sorry but I don't understand why you're using `electron-prebuilt` instead downloading it as needed from the official repo. But, @maxogden decoupled entire download process into separate module(s) called `electron-download` - which is responsible for downloading it. So maybe using that repo 'on demand' would help?

**Comment by mcfedr** [comment]
I am using tools like `electron-builder`, and it requires me to have `electron-prebuilt`, but the repo is a combined electron app and web app, i build on two build servers, so the web app build server always downloads electron even though it does need it.
Anyway, maybe I can find a work around at the other end of this issue.

**Comment by TekSiDoT** [comment]
I think this should be reconsidered. In our scenario, Electorn applications are built in a Docker environment running on a server that does not have outside access. It does however have access to a local package manager proxy and a cache directory of available electron versions.

`electron-download` can handle cached download directories (as used in electron-packager). It would be a matter of figuring out which method of configuration to use during the installation process.
