### ISSUE TITLE
Allow to install multiple binaries

### ISSUE THREAD

**Issue by silverkorn** [electron-userland/electron-prebuilt#126]
Related **NW.js** issue:
https://github.com/nwjs/npm-installer/issues/47

I was wondering if the electron prebuilt could install multiple binaries for different operating systems in a same place, so, by suggestion, by modifying the path of `./electron-prebuilt/dist/` to `./eletron-prebuilt/dist/win32-x64/`, `./eletron-prebuilt/dist/win32-ia32/`, `./eletron-prebuilt/dist/linux-x64/`, `./eletron-prebuilt/dist/darwin-x64/` and so on so it could be dynamically set with `process.platform` & `process.arch`.

Please, see my request for NW.js via their npm installer for details about the motivation.
Thank you!

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
