### ISSUE TITLE
Segmentation fault running electron with Raspberry pi 1 B model

### ISSUE THREAD

**Issue by wmehanna** [electron-userland/electron-prebuilt#142]
Running my app is giving me the following issue :

I'm trying to run electron on my rasperry pi 1 B but i'm geeting absolutly zero output from the CLI.

here's my detailed log using electron-quick-start project :

```
pi@raspberrypi:~ $ sudo npm install -g electron-prebuilt
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@1.2.0 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

Downloading electron-v1.2.0-linux-arm.zip
[============================================>] 100.0% of 35.79 MB (1.42 MB/s)
/usr/local/lib
└── electron-prebuilt@1.2.0 

pi@raspberrypi:~ $ git clone https://github.com/electron/electron-quick-start.git
Cloning into 'electron-quick-start'...
remote: Counting objects: 175, done.
remote: Total 175 (delta 0), reused 0 (delta 0), pack-reused 174
Receiving objects: 100% (175/175), 26.99 KiB | 0 bytes/s, done.
Resolving deltas: 100% (85/85), done.
Checking connectivity... done.
pi@raspberrypi:~ $ cd electron-quick-start/
pi@raspberrypi:~/electron-quick-start $ electron main.js 
pi@raspberrypi:~/electron-quick-start $ electron -v
pi@raspberrypi:~/electron-quick-start $ 
```

I'm running raspbian jessy freshly installed and upgraded with apt-get update and apt-get dist-upgrade

I tried using another raspberry pi 1 B with another SD card, but I'm still running this same issue.

Any idea what else I can do ?

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
