### ISSUE TITLE
Prebuilt MAS instead of Darwin for OS X

### ISSUE THREAD

**Issue by Allendar** [electron-userland/electron-prebuilt#143]
As there are some differences between what the MAS package has, I prefer to develop apps that go to the Mac App Store solely in the mas-specific build and not be surprised afterwards that things are a bit different when packing and signing.

I could just unzip the package at `~/.electron/electron-v1.2.0-mas-x64` to `/usr/local/lib/node_modules/electron-prebuilt/dist/` and it's done. But I'm also developing non-MAS apps that I want test in `darwin` builds.

Is there a way through the `electron` command or a project setting that can dynamically make the `electron` command pick `mas` or `darwin` as the package to run in while developing?

Thanks in advance!

**Comment by kevinsawicki** [comment]
> As there are some differences between what the MAS package has

Yes, certain APIs are unavailable in the MAS version, see http://electron.atom.io/docs/tutorial/mac-app-store-submission-guide/#limitations-of-mas-build for more details.

> Is there a way through the electron command or a project setting that can dynamically make the electron command pick mas or darwin as the package to run in while developing?

There is not, this is usually done by packaging different versions of your app using `electron-packager` and then launching the one you want to test.

**Comment by kof** [comment]
What happend to the `npm_config_platform=mas`, this has been working before during installation

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
