### ISSUE TITLE
How can I remove old version resources after auto-update?

### ISSUE THREAD

**Issue by lzdnku307** [electron-userland/electron-prebuilt#155]
After auto-update to the newest version, I find my app keep the old version resources:
![1 pic](https://cloud.githubusercontent.com/assets/14030095/16227069/26c6100c-37e1-11e6-953e-0d91ff847478.jpg)
Can I remove the old version resources? And how?

Note:
The option asar is false when I building my app.Electron-prebuit version is: 0.37.8
And I found when the app start, the old version's electron.asar is locked!

**Comment by kevinsawicki** [comment]
Squirrel for Windows, the auto update system for Electron, should eventually delete old versions once it can. This isn't explicitly managed by electron-prebuilt or electron itself, but completely by https://github.com/squirrel/squirrel.windows

If you are seeing old versions not being deleted eventually after updates, you may want to report an issue on https://github.com/squirrel/squirrel.windows/issues

Closing this out here since this isn't related to `electron-prebuilt`.
