### ISSUE TITLE
Electron prebuilt on Android

### ISSUE THREAD

**Issue by sarkande** [electron-userland/electron-prebuilt#161]
Hello,
when  i try to install electron-prebuilt with
`npm install`
i got this error

`/data/data/com.termux/files/home/electron-quick-start/node_modules/electron-prebuilt/install.js:32
if (!paths[platform]) throw new Error('Unknown platform: ' + platform)
                      ^

Error: Unknown platform: android
    at Object.<anonymous> (/data/data/com.termux/files/home/electron-quick-start/node_modules/electron-prebuilt/install.js:32:29)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3`

**Comment by zeke** [comment]
You're getting this error because the Electron project doesn't currently release a build for the Android platform.

Out of curiosity, what device and operating system version are you running? Electron currently produces an `armv7l` build (named `arm` on the [releases page](https://github.com/electron/electron/releases)), which may work for you if that's the hardware you're using, but that platform is not yet supported by `electron-prebuilt`

**Comment by sarkande** [comment]
I use a remix mini with the lastest version of remix os

**Comment by zeke** [comment]
According to [Amazon](https://www.amazon.com/Jide-Remix-Storage-Android-Desktop/dp/B0177OAIIK), your processor is:

> 1.2 GHz ARM7500FE

Which has an `ARM710a` core. So your device may technically be compatible with [the existing ARM build](https://github.com/electron/electron/releases) of Electron!

For updates on ARM support in Electron, you may want to subscribe to these issues:

- https://github.com/electron/electron/issues/5706
- https://github.com/electron/electron/issues/2343
- https://github.com/electron/electron/issues/259

**Comment by kevinsawicki** [comment]
@sarkande are you able to run the following on your machine and report back the output?

```
node -p "console.log(process.platform, process.arch, process.config.variables.arm_version)"
```

Thanks.

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
