### ISSUE TITLE
electron-prebuilt can't be used by electron forks with different versions

### ISSUE THREAD

**Issue by bridiver** [electron-userland/electron-prebuilt#192]
We have an electron fork at https://github.com/brave/electron. We have the same major/minor version number as upstream electron, but the patch version is often different and may not exist in upstream. We have to fork electron-prebuilt and update the version number in our fork for each release. Forking electron-prebuilt and updating for each release seems like a lot of unnecessary and I think it would be much better if the entire build process used env vars and/or npm config instead. This would eliminate the need to update electron-prebuilt for each release and make the release process much simpler. Other parts of the electron build process also read directly from the electron-prebuilt version so we can't even fix this problem in our fork without also forking basically all of the build repos

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
