### ISSUE TITLE
Setting 32/64-bit architecture in package.json

### ISSUE THREAD

**Issue by njbmartin** [electron-userland/electron-prebuilt#219]
* Electron version: 1.4.10
* Operating system: Win 10 (64-bit)

You can install and run a 32-bit version of Electron with `npm i electron --arch=ia32 --save` but package.json doesn't keep a record of the architecture, so when a second developer clones and runs `npm i`, the post-install of Electron downloads the 64-bit version by default.

We should be able to specify the architecture in `package.json` or in a .electron file for `electron-download` to use before defaulting to the OS.

Our team has a requirement to run a 32-bit version on Windows due to a PPAPI plugin restriction.

**Comment by zeke** [comment]
What if you set an `install` or `postinstall` script as a workaround?

```json
{
  "scripts": {
    "preinstall": "npm rm electron --save",
    "postinstall": "npm i electron --arch=ia32 --save"
  }
}
```

⚠️  This is a hack, but it might work in the short term.

**Comment by njbmartin** [comment]
Good suggestion, but this will only work on Windows and will break for Mac devs.

**Comment by njbmartin** [comment]
Once I have a spare moment, I'll have a go at implementing my suggestion.

**Comment by zeke** [comment]
> We should be able to specify the architecture in package.json or in a .electron file for electron-download to use before defaulting to the OS.

If you do end up doing this, I would vote for a package.json property, rather than a new file.

**Comment by njbmartin** [comment]
Ok. I dont think `"electron":{}` is already used in package.json?

I'm proposing the following:

```json
"electron": {
    "win32": {
        "arch": "ia32"
    }
}
```

With the intention of modifying `install.js` to check if config exists for the given platform, and if it does, use that to populate `download({})`

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
