### ISSUE TITLE
Unable to install (tunneling socket could not be established)

### ISSUE THREAD

**Issue by Craftiii4** [electron-userland/electron-prebuilt#235]
Using Windows 10 Pro, x64

Been trying to install electron but I've been unable to. The error makes me think it's a proxy issue but I seem to have no problem installing other packages.

> Error: tunneling socket could not be established, cause=read ECONNRESET
>     at ClientRequest.onError (*dir*\node_modules\tunnel-agent\index.js:177:17)
>     at ClientRequest.g (events.js:291:16)
>     at emitOne (events.js:96:13)
>     at ClientRequest.emit (events.js:188:7)
>     at TLSSocket.socketErrorListener (_http_client.js:310:9)
>     at emitOne (events.js:96:13)
>     at TLSSocket.emit (events.js:188:7)
>     at emitErrorNT (net.js:1278:8)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

Attached the full log

[2017-03-17T11_09_08_452Z-debug.log.txt](https://github.com/electron-userland/electron-prebuilt/files/850372/2017-03-17T11_09_08_452Z-debug.log.txt)

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
