### ISSUE TITLE
Should show the download progress or some kind of information if the download is slow

### ISSUE THREAD

**Issue by MarshallOfSound** [electron-userland/electron-prebuilt#236]
If the download takes more than a certain amount of time (let's just say 2 minutes) we should enable the progress output of `electron-download`.

The current user experience is to see `node install.js` and then sit there on their slow internet connection wondering why on earth it is taking so long.  Then the cancel it and start again not realizing it restarts the entire download and nothing was wrong in the first place.

I think the install flow should end up something like

```bash
npm i electron
# > executes node install.js
# Downloading prebuilt Electron binaries, on a slower internet connection this may time some time
# >Wait 2 minutes
# Looks like download Electron is taking a bit longer than normal, you can now see the download progress below
# [#####----------------------------] 20%
```

This way for the average user with decent internet the experience will be the same, for users with this "my terminal does nothing" issue we will at least be warning them it might take a while, and then giving the information they want to see after a given amount of time.

Feedback welcome, just a proposal 👍

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!

PS Love this idea. :)
