### ISSUE TITLE
can't install electron from mirrors with 302 redirect..yet

### ISSUE THREAD

**Issue by Zougi** [electron-userland/electron-prebuilt#238]
I have an issue _installing_ Electron.
Particulary at the download phase. I'm using a mirror hosted on sonatype nexus

* Electron version: all
* Operating system: all

So I set the needed environment variables in order to download electron from the mirror

- ELECTRON_MIRROR
- ELECTRON_CUSTOM_DIR
- ELECTRON_CUSTOM_FILENAME

install.js file throw an exception because the link sends a 302 response code (redirect) but electron-prebuilt uses nugget package to download the package and nugget do not follow redirect responses...ok but nugget has a force argument. I edited the code to put this argument to true...that worked and downloaded the package to electron download cache but install.js failed again because no checksum could be found on the address I gave with ELECTRON_MIRROR 

I opened PR https://github.com/electron-userland/electron-download/pull/53 to fix these problems, could you review it and update electron-prebuilt with new version of electron-download when you have a chance?

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
