### ISSUE TITLE
Mac: Failed at the electron@1.6.8 postinstall script 'node install.js'.

### ISSUE THREAD

**Issue by ryan-christopher** [electron-userland/electron-prebuilt#254]
Received the following message:

Failed at the electron@1.6.8 postinstall script 'node install.js'. (Exit Status 1)

node.js (and I assume npm with it) were just downloaded and installed from their site.

* Electron version: electron@1.6.8
* Operating system: macOS Sierra 10.12.4

I'm brand new to working with these types of files and installers, so I'm not sure how to correct this.
Also, I need to know if I can do this as a global install, as I would not like to confront the prospect of installing this in every single project folder.

**Comment by shakhassan** [comment]
In my case, `npm install electron -g` will do the trick.

**Comment by firsttracks** [comment]
I am seeing the same error.  Is there a work around for this issue?

**Comment by firsttracks** [comment]
I got around this issue by looking at the link "https://docs.npmjs.com/getting-started/installing-npm-packages-locally".  I tried a bunch of things and not sure exactly what fixed it but I did run "npm init" with defaults and then the "npm install mapbox-map-image-export -g" command seemed to work

**Comment by aliir74** [comment]
I've got the same error.
**electron@1.6.11 postinstall: `node install.js`. Exit status 1**
* Node.js version: v8.1.4
* Electron version: v1.6.11
* OS: Ubuntu 16.04

**Comment by aliir74** [comment]
@ryan-christopher I updated my node to last version and the error fixed.

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
