### ISSUE TITLE
Prebuilt electron package for Ubuntu 10.04 32 bits

### ISSUE THREAD

**Issue by luimucar** [electron-userland/electron-prebuilt#268]
If you're having an issue _installing_ Electron, this is the place to report it.

If you're having an issue _using_ Electron, please report it at https://github.com/electron/electron/issues

* Electron version:
1.6.11
* Operating system:
Ubuntu 10.04 32 bits (have to use this old one :( )

I am not able to run easily the prebuilt electron in the ubuntu 10.04. The problems I get can be solved manually (install the libxss1 and upgrade the libnss3). I am trying to make a distribution package to deliver a deb or an AppImage for this ubuntu 10.04 32bits. But in all cases, the package fails to install and complains for the missing libs in the system (libxss1 / libnss3) ls there a way to create a deb/AppImage handling (including) these missing libraries? Do I have to compile electron in this ubuntu? Thanks in advance, magnific tool, electron by the way.

**Comment by zeke** [comment]
The [electron-prebuilt repo is being retired](https://github.com/electron-userland/electron-prebuilt/pull/275) and its code has been moved into the electron/electron repo. For the sake of historical transparency, we will leave GitHub Issues enabled on this repository, but if you are still affected by the issue reported here, please [open a new issue on electron/electron](https://github.com/electron/electron/issues/new) repo and reference this issue from it so people can get the full context. The electron repository has a large and active contributor community, so your issue is more likely to get the attention it deserves there. Thanks!
