### ISSUE TITLE
Electron installation fails on Debian based distros.

### ISSUE THREAD

**Issue by saq1610** [electron-userland/electron-prebuilt#70]
I have been trying to install electron on my Ubuntu system both as a dependancy and globally but both commands fail.
Here is the output:
```
saq1610@saq1610-MacBookPro:~/Watson$ sudo npm install electron-prebuilt -g
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.35.1 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! electron-prebuilt@0.35.1 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.35.1 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.2.0-19-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron-prebuilt" "-g"
npm ERR! cwd /home/saq1610/Watson
npm ERR! node -v v4.2.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/saq1610/Watson/npm-debug.log
npm ERR! not ok code 0
saq1610@saq1610-MacBookPro:~/Watson$ 
```
According to the log in `/usr/share/doc/nodejs/README.Debian` this seems to be the issue:

```
nodejs command
--------------

The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".

This was done to prevent a namespace collision: other commands use
the same name in their upstreams, such as ax25-node from the "node"
package.

Scripts calling Node.js as a shell command must be changed to instead
use the "nodejs" command.
```
It seems that electron still calls upon "node" rather than "nodejs" which is why the "install.js" script fails.

**Comment by maxrimue** [comment]
As it says `node: not found`, we can expect your system to not be affected by problems in case Node.js uses the command `node`, so, as a temporary solution, you could create an alias like this:
```
alias node='nodejs'
```
The alias will only be valid during that terminal session which means you're safe in case you'll ever have another program using `node` as its command. After setting the alias, install again, it should work after that without using an alias.

**Comment by tomwor** [comment]
The alias doesn't work. It seems the npm process spawns another process where the alias is not recognized?
Another thing that caught my eye: the node_modules folder is empty after the error.
If the post install script doesn't run, does the whole package get removed again?
Shouldn't it be in there?

**Comment by maxrimue** [comment]
@tomwor Yeah, it's possible that npm spawns a process that is not affected by this way of aliasing. It could also be that npm deletes the dependency folder in `node_modules/` if installation has failed, probably because you can't just resume the installation process if it has failed at some point, so it rather asks you to download it again (if not cached) and start the installation again from zero.

It's also possible that not every Debian user will even install the ax25-node package (or others using the `node` command), to be honest, `node` is a really bad name for a command since it's just as descriptive as `webbrowser` or something like that, maybe it'll even be changed in the future as Node.js is getting more popular everyday. On [packages.debian.org](https://packages.debian.org/en/sid/hamradio/ax25-node), it is described like this:
> The ax25-node program accepts TCP/IP and packet radio network connections and presents users with an interface that allows them to make gateway connections to remote hosts using a variety of amateur radio protocols.

Another way for making the alias available globally is to create the alias in your `.bashrc` file, but you can of course also use `sudo ln -s`.

**Comment by ngoldman** [comment]
I recommend trying out https://packages.debian.org/sid/nodejs-legacy, that seems to have worked for others having issues installing on different linux distros.

```
sudo apt-get install nodejs-legacy
```

See https://github.com/electron-userland/electron-prebuilt/issues/27#issuecomment-181583077 for an example that resolved a similar issue. Marking this as resolved as it sounds like `nodejs-legacy` was made to deal with this issue.
